### ISSUE TITLE
Unable to run sample app

### ISSUE THREAD

**Issue by mlhDevelopment** [deMD/UmbracoContentApi#33]
I'm unable to run the UmbracoContentApi.Umbraco9 nor the UmbracoContentApi.Web project.

UmbracoContentApi.Umbraco9 (styled as a website) runs but produces a "ArgumentException: Value cannot be null or empty. (Parameter 'viewName')" error.

UmbracoContentApi.Web (mentioned in issue #27) does not run, it produces an 'output type of class library cannot be started' message.

How do you run the sample app for Umbraco 9?

Using VS 2022 (17.0.0)
dotnet v6.0.100
Win10 21H1

**Comment by deMD** [comment]
I'll make sure there is a swagger for the sample app as a starting page. Currently the error is expected as the sample app is purely an API without views.

Reason you get that message for the web project is because it's a class library and not a running application, I moved code over time to be more self contained (umbraco is in the .Umbraco project, executing code is in the .Web project and Core implementations are in the .Core project).

**Comment by mlhDevelopment** [comment]
I didn't even think about that, I just thought it would have been a full Umbraco install (though it was a little light). Yes, I can get to https://localhost:44312/swagger/index.html

**Comment by deMD** [comment]
Just merged PR #34 so that Swagger now opens at the root of the site.
